# .github/workflows/deploy-presentation.yml

name: Build and Deploy - ServerSide-Web-Programming (Presentation)

on:
  push:
    branches:
      - development   # Trigger deployment when pushing to 'development'
  workflow_dispatch:  # Allow manual trigger

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./Presentation/ServerSide-Web-Programming/ServerSide-Web-Programming.csproj

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ./Tests/Tests.csproj --configuration Release --no-build --verbosity normal

      - name: Publish
        run: dotnet publish ./Presentation/ServerSide-Web-Programming/ServerSide-Web-Programming.csproj -c Release -o ./publish
      
      - name: Publish API app
        run: dotnet publish ./API/ServerSide-Web-Programming-API/ServerSide-Web-Programming-API.csproj -c Release -o ./publish/api

      - name: Upload published Presentation app
        uses: actions/upload-artifact@v4
        with:
          name: presentation-app
          path: ./publish/presentation
          
      - name: Upload published API app
        uses: actions/upload-artifact@v4
        with:
          name: api-app
          path: ./publish/api

  deploy_presentation:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Download Presentation artifact
        uses: actions/download-artifact@v4
        with:
          name: presentation-app

      - name: Deploy to Azure Web App (Presentation)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ServerSide-Web-Programming'    
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5DE8B11889BE453C9C8D4AAF605FAB78 }}
          package: .
          
  deploy_api:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Download API artifact
        uses: actions/download-artifact@v4
        with:
          name: api-app

      - name: Deploy to Azure Web App (API)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ServerSide-Web-Programming-API'   
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_API }}
          package: .
